// <auto-generated />
using System;
using MendMissionControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MendMissionControlAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609214632_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("MendMissionControl.Api.Models.DetritoOrbital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("AltitudeKm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("CodigoCatalogo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("DataIdentificacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("MassaKg")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Removido")
                        .HasColumnType("NUMBER(1)");

                    b.Property<double>("TamanhoCm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("VelocidadeKmh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCatalogo")
                        .IsUnique();

                    b.ToTable("DetritosOrbitais");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.EquipamentoEspacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CodigoIdentificacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoEquipamento")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIdentificacao")
                        .IsUnique();

                    b.ToTable("EquipamentosEspaciais");

                    b.HasDiscriminator<string>("TipoEquipamento").HasValue("EquipamentoEspacial");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.MendCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("MissaoRemocaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorCredito")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoRemocaoId");

                    b.ToTable("MendCredits");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.MissaoRemocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataPlanejada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DetritoOrbitalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MetodoRemocao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NaveLimpezaOrbitalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeMissao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DetritoOrbitalId");

                    b.HasIndex("NaveLimpezaOrbitalId");

                    b.ToTable("MissoesRemocao");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.Telemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NaveLimpezaOrbitalId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("NivelBateria")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("TemperaturaInterna")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("VelocidadeKmh")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("NaveLimpezaOrbitalId");

                    b.ToTable("Telemetrias");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.NaveLimpezaOrbital", b =>
                {
                    b.HasBaseType("MendMissionControl.Api.Models.EquipamentoEspacial");

                    b.Property<double>("CapacidadeCombustivel")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<bool>("PossuiGarrasCaptura")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("PossuiLaserAblacao")
                        .HasColumnType("NUMBER(1)");

                    b.HasDiscriminator().HasValue("NAVE_LIMPEZA_ORBITAL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIdentificacao = "MEND-ORION-001",
                            DataLancamento = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Orion",
                            CapacidadeCombustivel = 1000.0,
                            PossuiGarrasCaptura = true,
                            PossuiLaserAblacao = true
                        });
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.Satelite", b =>
                {
                    b.HasBaseType("MendMissionControl.Api.Models.EquipamentoEspacial");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("SATELITE");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.MendCredit", b =>
                {
                    b.HasOne("MendMissionControl.Api.Models.MissaoRemocao", "MissaoRemocao")
                        .WithMany()
                        .HasForeignKey("MissaoRemocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissaoRemocao");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.MissaoRemocao", b =>
                {
                    b.HasOne("MendMissionControl.Api.Models.DetritoOrbital", "DetritoOrbital")
                        .WithMany("Missoes")
                        .HasForeignKey("DetritoOrbitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MendMissionControl.Api.Models.NaveLimpezaOrbital", "NaveLimpezaOrbital")
                        .WithMany()
                        .HasForeignKey("NaveLimpezaOrbitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetritoOrbital");

                    b.Navigation("NaveLimpezaOrbital");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.Telemetria", b =>
                {
                    b.HasOne("MendMissionControl.Api.Models.NaveLimpezaOrbital", "NaveLimpezaOrbital")
                        .WithMany()
                        .HasForeignKey("NaveLimpezaOrbitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NaveLimpezaOrbital");
                });

            modelBuilder.Entity("MendMissionControl.Api.Models.DetritoOrbital", b =>
                {
                    b.Navigation("Missoes");
                });
#pragma warning restore 612, 618
        }
    }
}
